### ISSUE TITLE
Consider introspection for checking if a contract implements ITeleporterReceiver

### ISSUE THREAD

**Issue by michaelkaplan13** [ava-labs/teleporter#108]
**Context and scope**
A contract that would like to receive messages from the `TeleporterMessenger` contract must implement the `receiveTeleporterMessage` function from the `ITeleporterReceiver` interface. This function is called when the message is being executed. If a contract does not implement the `receiveTeleporterMessage` function, the call will fail and be stored for a future execution. However, if the receiving contract does not implement this function and instead implements a fallback , the call could be successful. This opens up the possibility whereby even though the message is being forwarded to the contract, the destination contract does not handle it but there is no reversion of the transaction. 

In favor of restricting the possibility of a message being delivered into a non-compatible contract on the destination subnet, consider using an EIP meant for introspection, such as [EIP-1820](https://eips.ethereum.org/EIPS/eip-1820), instead of assuming that contracts that do not possess a `receiveTeleporterMessage` hook cannot be called.

**Open questions**
Is this worth the additional complexity in the `TeleporterMessenger` contract, given that it is the responsibility of the application contracts using Teleporter to ensure they properly implement the required interface and are able to process intended message properly?

**Comment by cam-schultz** [comment]
[ERC-1820](https://eips.ethereum.org/EIPS/eip-1820) adds complexity to a handful of areas that we would want to think carefully about before implementing. In descending order of the amount of work required to support, ERC-1820:
- Requires a registry be deployed to each chain using Nick's method. This is straightforward, but would be an additional step subnets would need to take in order to be compatible with Teleporter
- Requires dApp contracts to follow a specific set of steps in order to register as an implementer of an interface. There's a fair amount of flexibility with respect to who can register a contract as an implementer, which we'd want to make sure we fully understand. Even if a dApp contract is ERC-1820 compliant, there's no guarantee that the `receiveTeleporterMessage` implementation is bug-free
- And of course TeleporterMessenger itself would need to handle the case in which a destination address doesn't implement the interface according to the ERC

**Comment by minghinmatthewlam** [comment]
For the considerations noted above, closing issue. Also we revisited if current approach for limitations/vulnerabilities, and want to document interaction with fallback functions, new issue [here](here), but TLDR no vulnerabilities, as in the dapp's repsonsibility to implement `receiveTeleporterMessage` to receive messages.
