### ISSUE TITLE
"Validator Set Signature" Contract Utility

### ISSUE THREAD

**Issue by michaelkaplan13** [ava-labs/teleporter#398]
**Context and scope**
[Off-chain Warp messages](https://github.com/ava-labs/subnet-evm/issues/729) provide a mechanism for validator to sign arbitrary messages using their BLS keys in a way that enables Warp-enabled VMs to verify that a threshold of stake weight of a given validator set has signed the message. This could be leveraged as an authentication mechanism for smart contracts.

Similarly to how [Safe multi-sig contracts ](https://github.com/safe-global/safe-smart-account/tree/main/contracts) require signatures to be provided from K of N participates in order to execute the input calldata, a `ValidatorSetSig` contract could require a threshold of a given Subnet's validator set to provide a signature in order to execute input calldata.

The would unlock the notion of "Subnet-owned" smart contracts. Instances of these could be used as the admin of other contracts such that admin actions could only be taken a threshold of stake of a given Subnet signs off on the action. These contracts could be deployed on any Warp-enabled chain, no matter which Subnet validator set is required to provide its signature. For instance, you could have a contract on the C-Chain that requires a Warp signature from a specific Subnet, or you could have a contract on a Subnet that requires a Warp signature from its own validators (a form of off-chain governance).

**Open questions**
- How to handle replay protection of messages?
   - The Safe multi-sig contracts use basic nonce tracking.
- How to ensure that messages only have effect on the target contracts on the target chains (i.e cross-chain replay protection).

**Comment by minghinmatthewlam** [comment]
should this contract have a `modifier` for contracts that want add a similar check functionality to their function calls?

**Comment by michaelkaplan13** [comment]
Sorry not sure I follow what you mean. I think the common pattern for this type of contract would be to make it the `owner` of other contracts such that functions on that contract with the `onlyOwner` modifier are only able to called when a threshold of stake weight of the given Subnet signs off on the call being made.

**Comment by geoff-vball** [comment]
Could you elaborate on exactly what advantages this provides over using off-chain warp messages directly?

**Comment by michaelkaplan13** [comment]
> Could you elaborate on exactly what advantages this provides over using off-chain warp messages directly?

IMO, the primary benefit is abstracting away all of the authentication logic from application contracts, similar to how is done in commonly with multi-sigs and/or DAOs that are given elevated permissions in applications.

Say an application `MyContract` has function `setConfiguration(...)` that takes a few arbitrary parameters. Instead of needing providing its own authentication logic for the requirements of calling `setConfiguration`, it just adds the `onlyOwner` modifier to it. Then the function can can be gated behind any of EOA/multi-sig/DAO vote/validator set signature/etc, by just specifying the address of the "owner".

**Comment by iansuvak** [comment]
Confirming that I am thinking about replay protections correctly. 

We want to ensure the following about the off-chain warp message whose id we pass into the `ValidatorSetSig` contract:

1.  `warpMessage.sourceChainID == address(0)` -- This is to prevent this contract from being called by a on-chain warp message. 
2. `warpMessage.payload == abi.encode(targetBlockChainID, validatorSetSigNonce, abi.encodeWithSelector("<target function signature>", <target function calldata>)` -- Having all of this signed by the validators of the source chain confirms that the message was intended to be sent to `ValidatorSetContract`'s block chain and that it can't be replayed later on the same chain. 

Is this correct? 

Additionally we could have the nonce be handled as a singleton or `mapping(targetContractAddress => nonce)`. I'm leaning towards the latter since this is intended for off-chain governance and the presumably the coordination for getting the message signed by validator quorum takes some time.  If using a single nonce with a single `ValidatorSetSig` contract being used as owner of multiple downstream contracts there could be a collision where the nonce gets consumed before the message is processed. This would be a bad experience and would require another round of coordination at the cost of using more storage.

**Comment by cam-schultz** [comment]
> 2. warpMessage.payload == abi.encode(targetBlockChainID, validatorSetSigNonce, targetContractAddress, abi.encodeWithSelector("<target function signature>", <target function calldata>)

I'm not sure if this is what you meant, but we should only need to verify the targetBlockChainID, targetContractAddress, and nonce. We don't want to generically verify function selectors and their args.

**Comment by cam-schultz** [comment]
One other thought, we may want to consider separating the execution of the `ValidatorSetSig` contract call from the target function call, like how we do so for `TeleporterMessenger`. That way relayers have an incentive to deliver these messages even if the target function call fails. OTOH, the frequency of these messages may be low, and if used as a governance mechanism, there's already a strong (non-financial) incentive to deliver these messages anyway - so it may not be worth the added complexity to implement execution separation here.

**Comment by iansuvak** [comment]
> > 2. warpMessage.payload == abi.encode(targetBlockChainID, validatorSetSigNonce, targetContractAddress, abi.encodeWithSelector("", )
> 
> I'm not sure if this is what you meant, but we should only need to verify the targetBlockChainID, targetContractAddress, and nonce. We don't want to generically verify function selectors and their args.

Yeah sorry. My annotation was clumsy but we are on the same page. I didn't mean to imply that we should verify the function selector or the args (it's clearly impossible). Just wanted to represent the whole of the warpMessage.payload field using the `==` there was wrong. 

re: separating execution and delivery. I will read the `TeleporterMessenger` contract more thoroughly and think about it more.
