### ISSUE TITLE
Handle changing stake weight

### ISSUE THREAD

**Issue by cam-schultz** [ava-labs/teleporter#440]
**Context and scope**
The Staking Contracts should support changing a validator's stake weight without having to wait for the validation to end or be cancelled. The function that's used to adjust the stake weight can be used to implement delegation, as well as implement validator removal. Both flows result in a `SetSubnetValidatorWeightTx` on the P-Chain

**Comment by michaelkaplan13** [comment]
From a feature perspective, we shouldn't consider it a requirement for a validator to change their weight of their active validation period. I think that comes with some unnecessary complexity of reward calculation, etc. But we will need to support delegations beginning and ending, which will require sending `SetSubnetValidatorWeight` messages to the P-Chain as you mentioned. 

Wanted to call this out because I think could affect the contract interface functions.

**Comment by cam-schultz** [comment]
Closing in favor of Delegation features (#441)
