### ISSUE TITLE
Allow users to Delegate Stake

### ISSUE THREAD

**Issue by geoff-vball** [ava-labs/teleporter#441]
**Context and scope**
The staking contract should have an external function for users to delegate tokens for a validator to stake for them.

**Discussion and alternatives**
This will require sending a `SetSubnetValidatorWeightTx` message to the p-chain to update the validator's stake weight.

**Open questions**
Parameters on how rewards are shared.

**Comment by michaelkaplan13** [comment]
Noting some loose delegation design thoughts here that will need to be iterated on:
- Delegation only applies for PoS validator manager contracts. PoA does not need delegation.
- For primary network validation currently, there are explicit end times to the validation period, and a max possible end time of the end of the validator's validation period that is being delegated to. That is not the case with the continuous staking mechanism in the validator manager contract. Delegations will not have any defined end time, but will end either when:
    - The delegator explicitly ends their delegation period by interacting with the contract
    - The validation period that was delegated to ends.

### Adding a new delegator

When creating a new delegation, a function akin to `initializeAddDelegation` should be called, which will lock however much stake is provided in the contract, and specify which `validationID` is to be delegated to. This call should send a [`SubnetValidatorWeightUpdateMessage`](https://github.com/avalanche-foundation/ACPs/tree/main/ACPs/77-reinventing-subnets#subnetvalidatorweightupdatemessage) with an incremented nonce and weight value for the given `validationID`. The current nonce and weight for each validation ID must be tracked by the contract.

Similar to the validator initialization flow, after `initializeAddDelegation` is called, the delegator will have to deliver the `SubnetValidatorWeightUpdateMessage` message it emitted to the P-Chain as part of a [`SetSubnetValidatorWeightTx`](https://github.com/avalanche-foundation/ACPs/tree/main/ACPs/77-reinventing-subnets#setsubnetvalidatorweighttx).

The delegator then must relay proof that the `SubnetValidatorWeightUpdateMessage` message was delivered to the P-Chain back to the validator manager contract by calling a `completeAddDelegation` function. This is the point when the delegation start time should be locked in as far as rewards beginning to accrue. This proof will be provided to the contract in the form of a [`SubnetValidatorWeightUpdateMessage`](https://github.com/avalanche-foundation/ACPs/tree/main/ACPs/77-reinventing-subnets#subnetvalidatorweightupdatemessage) from the P-Chain with a `nonce` value **greater than or equal to** the nonce used for to create the given delegation period. 

The P-Chain is only willing to accept `SubnetValidatorWeightUpdateMessage`s with nonces greater than the latest nonce used for the given `validationID`. This means that if nonces 1 and 2 are sent by the contract in quick succession, and then a message with nonce 2 is delivered to the P-Chain first, the message with nonce 1 will never be able to be delivered. However, these messages each have accumulating/commutative effects. For instance, if the `validationID` previously had a weight of 10, and each of the `SubnetValidatorWeightUpdateMessage`s added 3 to the `validationID` weight, then the message with nonce 1 would specify a weight of 13, and the message with nonce 2 would specify a weight of 16. The fact that message with nonce 2 was delivered to the P-Chain means that all changes in messages with nonce <=2 have also taken effect. The same applies for messages that reduce the `validationID`'s weight when delegations are ended.

Because of this a `completeAddDelegation` function can be called to complete the registration of a given `delegationID` **(still need to determine how a unique `delegationID` will be represented)**, with any signed [`SubnetValidatorWeightUpdateMessage`](https://github.com/avalanche-foundation/ACPs/tree/main/ACPs/77-reinventing-subnets#subnetvalidatorweightupdatemessage) from the P-Chain with a `nonce` value **greater than or equal to** the nonce used for to create the given delegation period. 

### Ending a delegation period

If a validation period for a given `delegationID` is ended prior to the delegation period being ended first, the delegation stake will still be locked in the contract, but rewards will stop accruing on it. It is the responsibility of delegators to monitor if this occurs.

If a delegator wants to end their delegation period prior to the end of the validation period, they can do so by calling a `initializeEndDelegation` method, which should send a `SubnetValidatorWeightUpdateMessage` message to the P-Chain with an incremented nonce and decremented weight for the given `validationID`. This message then must be delivered on the P-Chain, and proof of it's delivery on the P-Chain must be relayed back to the contract as part of a `completeEndDelegation` call for the locked funds to be unlocked and any rewards to be issued. Similar to the add delegator flow, any `SubnetValidatorWeightUpdateMessage` with a nonce greater than or equal to the nonce used for the message removing the delegation weight is sufficient for proving its delivery.

In the event that the `validationID` ends prior the delegation being ended, `completeEndDelegation` (or another function) should also be able to be called with proof that the `validationID` is now invalidated on the P-Chain (i.e. [`SubnetValidatorRegistrationMessage`](https://github.com/avalanche-foundation/ACPs/tree/main/ACPs/77-reinventing-subnets#subnetvalidatorregistrationmessage) with `registered = false`).

**Comment by bernard-avalabs** [comment]
> If a validation period for a given delegationID is ended prior to the delegation period being ended first, the delegation stake will still be locked in the contract, but rewards will stop accruing on it. It is the responsibility of delegators to monitor if this occurs.

I assume this means that a delegator should manually end the delegation period (and possibly redelegate to a different validator) once it has determined this has happened. Otherwise their stake will be still be locked but will not be earning rewards. Wouldn't this hurt the UX of delegators who just want to set and forget a relatively long delegation period?

**Comment by michaelkaplan13** [comment]
> I assume this means that a delegator should manually end the delegation period (and possibly redelegate to a different validator) once it has determined this has happened. Otherwise their stake will be still be locked but will not be earning rewards.

Yeah that's correct.

> Wouldn't this hurt the UX of delegators who just want to set and forget a relatively long delegation period?

Yeah great point...it definitely is a worse UX for delegators, because with continuous staking there is no way to know that given validation period will last for any amount of time into the future.

Trying to think of a way to improve this UX now. One option could be to add an extension to the PoS validator manager contract that allows a staker to specify a `minimumEndTime` when they call `initializeAddValidator`, and disallow `initializeEndValidator` from being called prior to that end time for the validation period. That way delegators would know the minimum length that the staker is locked in for.

**Comment by minghinmatthewlam** [comment]
>If a validation period for a given delegationID is ended prior to the delegation period being ended first, the delegation stake will still be locked in the contract, but rewards will stop accruing on it. It is the responsibility of delegators to monitor if this occurs.

On a high level I was thinking the PoS validator manager contract would be able to track which `validationID` a delegation corresponds to. In the case, a validation ends before the delegation, thinking if it's possible for the contract to end the related delegations as well and distribute the rewards to the delegators. 

> Generally speaking, uptimes for delegation periods should be able to be provided in initializeEndDelegation calls, and if the validation period was ended prior to the delegation ending, the uptime provided when ending the validation period should be used to calculate the rewards for the delegation when completeEndDelegation is called, since uptimes are only tracked for active validators and cleaned up when validators are removed.

How would rewards be calculated for delegators that joined in the middle of a validation period? If a delegator joined in the middle of the validation period, don't think it makes sense for them to simply have a proportional amount of rewards based just on their stake weight, and should also take into account the proportion of time they were delegated. In which case, the contract will probably need to track when a delegation joined a `validationID`. 

> When creating a new delegation, a function akin to initializeAddDelegation should be called, which will lock however much stake is provided in the contract, and specify which validationID is to be delegated to. 

Is there a use case for delegating to a `nodeID` that hasn't created an active validator yet? For example, if there's a node that simply runs validator services, but doesn't supply its own funds to reach the minimum stake amount. Then delegators could delegate to the node before an active `validationID` was created, then when the node goes to `initializeValidatorRegistration`, existing delegations would be contributing to the node's needed stake. Alternatively though, this could be abstracted a layer above, where an app accumulates user funds and submits an `initializeValidatorRegistration` through those funds.
