### ISSUE TITLE
Validators calling initializeEndValidation are required to submit an uptime proof

### ISSUE THREAD

**Issue by geoff-vball** [ava-labs/teleporter#557]
**Context and scope**
We have decided that validators must provide *some* valid uptime proof in order to end their validation. This is because other validators will stop tracking uptime for a validator that has called `initializeEndValidation`. To stop a validator from accidentally or maliciously not providing an uptime proof, we will require one. This proof will not be required to hit any sort of threshold for uptime, because even validators with low uptime should be able to exit the system.

**Discussion and alternatives**

**Open questions**
This may break current testing flows and require a larger refactor.

**Comment by cam-schultz** [comment]
As an optimization, we could cache the latest known uptime (submitted via `initializeEndDelegation`, or perhaps a standalone `submitUptimeProof`) and remove the uptime proof requirement on `initializeEndValidation` if the cached uptime is sufficient to collect rewards. The case we're trying to avoid here is accidental disqualification of rewards due to a missed uptime proof submission, and this would cover this.

Actually, this may not be solely an optimization, since a `submitUptimeProof` method would allow _anybody_ to update the cached uptime proof, decreasing the validator's ability to disqualify delegators from redeeming rewards.
